import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

const double kIndentationY = 30.0;
const double kIndentationX = 65.0;
const double kStepY = 50;
const double kStepX = 100;
const double kStockPaddingLeft = 20;
const double kStockPaddingTop = 20;
const double kStockPaddingRight = 20;
const double kStockPaddingBottom = 20;
const Color kLineColor = Colors.white12;
const Color kAxisColor = Colors.white60;
const TextStyle kTextAxisStyle = TextStyle(color: Colors.white60, fontSize: 11);
const int kMaxNumbers = 7;
const Duration kOneMinStep = Duration(minutes: 15);
const Duration kThreeMinStep = Duration(hours: 1);
const Duration kFiveMinStep = Duration(hours: 1, minutes: 30);
const Duration kTenMinStep = Duration(hours: 3);
const Duration kFifteenMinStep = Duration(hours: 6);
const Duration kHourStep = Duration(days: 1);
const Duration kDayStep = Duration(days: 30);
const Duration kWeekStep = Duration(days: 3 * 30);
const Duration kMonthStep = Duration(days: 2 * 365);
final DateFormat kHourMinuteFormat = DateFormat.jm('ru');
const double kCrossLineWidth = 2;
const Color kCrossColor = Colors.black;
const double kCrossSize = 16;
const double kCrossSubstrateSize = 2;
const Color kCrossSubstrateColor = Colors.white;
const double kDashWidth = 5;
const double kDashSpace = 5;
const Color kDashColor = Colors.white30;
const TextStyle kTextPriceStyle = TextStyle(color: Colors.white, fontSize: 12);
const double kTextPricePadding = 4;
final DateFormat kPriceDateFormat = DateFormat('d MMM yy HH:mm', 'ru'); // "27 Апр'21 9:45"
const Color kTextPriceBackgroundColor = Color(0xff757575);
